-- local lsp = require("lspconfig")
--
-- local servers = {
-- 	prolog_lsp = {
-- 		cmd = {
-- 			"swipl",
-- 			"-g",
-- 			-- "use_module(library(lsp_server)).",
--       "use_module([library(/home/juanro/.local/share/nvim/lazy/lsp_server/prolog/lsp_parser)]).",
-- 			"-g",
-- 			"lsp_server:main",
-- 			"-t",
-- 			"halt",
-- 			"--",
-- 			"stdio",
-- 		},
-- 		filetypes = "prolog",
-- 	},
-- }
--
-- for server, config in pairs(servers) do
-- 	config = vim.tbl_deep_extend("keep", config, {
-- 		capabilities = require("cmp_nvim_lsp").default_capabilities(vim.lsp.protocol.make_client_capabilities()),
-- 		on_attach = function()
-- 			vim.keymap.set("n", "ga", vim.lsp.buf.code_action)
-- 			vim.keymap.set("n", "gd", function()
-- 				require("telescope.builtin").diagnostics()
-- 			end)
-- 			vim.keymap.set("n", "gi", function()
-- 				require("telescope.builtin").lsp_implementations()
-- 			end)
-- 			vim.keymap.set("n", "gr", function()
-- 				require("telescope.builtin").lsp_references()
-- 			end)
-- 			vim.keymap.set("n", "gs", function()
-- 				require("telescope.builtin").spell_suggest()
-- 			end)
-- 			vim.keymap.set("n", "K", vim.lsp.buf.hover)
-- 		end,
-- 	})
--
-- 	lsp[server].setup(config)
-- end

-- local configs = require("lspconfig/configs")
-- local util = require("lspconfig/util")
--
-- configs.prolog_lsp = {
-- 	default_config = {
-- 		cmd = {
-- 			"swipl",
-- 			"-g",
--       -- "use_module(library('/home/juanro/.local/share/nvim/lazy/lsp_server/prolog/lsp_server.pl')).",
--       "use_module(library(lsp_server)).",
-- 			"-g",
-- 			"lsp_server:main",
-- 			"-t",
-- 			"halt",
-- 			"--",
-- 			"stdio",
-- 		},
-- 		filetypes = "prolog",
-- 		root_dir = util.root_pattern("pack.pl"),
-- 	},
-- 	docs = {
-- 		description = [[
--   https://github.com/jamesnvc/prolog_lsp
--
--   Prolog Language Server
--   ]],
-- 	},
-- }
-- vim:et ts=2 sw=2
